# .../setup/docker/docker-compose.yml
version: '3'
services:

  # Two cyboard containers are used for the CTF & Service Checker components
  server:
    image: cyboard:latest
    # build cyboard at the root of the git repo
    build:
      context: ../..
      dockerfile: setup/docker/Dockerfile
    entrypoint: dumb-init -- wait-for db:5432 -- cyboard server
    ports:
      - 80:8080
      - 443:8081
    volumes:
      - ../../data:/cyboard/data
      - ../../cfg:/home/cyboard/.cyboard/:ro
    environment:
      CY_POSTGRES_URI: "user=cybot password=${POSTGRES_PASSWORD:-} host=db sslmode=disable"
    links:
      - db

  checks:
    image: cyboard:latest
    # build cyboard at the root of the git repo
    build:
      context: ../..
      dockerfile: setup/docker/Dockerfile
    entrypoint: dumb-init -- wait-for db:5432 -- cyboard checks
    volumes:
      - ../../data:/cyboard/data
      - ../../cfg:/home/cyboard/.cyboard/:ro
    environment:
      CY_POSTGRES_URI: "user=cybot password=${POSTGRES_PASSWORD:-} host=db sslmode=disable"
    links:
      - db

  db:
    image: cyboard-db:latest
    # build from postgres-setup folder
    build: ../../migrations
    volumes:
      - db-data:${PGDATA:-/var/lib/postgresql/data}
    environment:
      - POSTGRES_PASSWORD
    expose:
      - "5432"

volumes:
  db-data:

